### ISSUE TITLE
Error building git with gui support.

### ISSUE THREAD

**Issue by CamilleScholtz** [sabotage-linux/gettext-tiny#16] opened 2017-10-23 20:07 UTC
Running gettext-tiny 0.2.0 on CRUX, I'm 80% sure this is a gettext-tiny caused error:

```
    SUBDIR git-gui
GITGUI_VERSION = 0.21.GITGUI
    * new locations or Tcl/Tk interpreter
    MSGFMT po/pt_pt.msg     MSGFMT    po/ru.msg make[1]: *** [Makefile:252: po/pt_pt.msg] Error 127
    MSGFMT    po/ja.msg make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:252: po/ru.msg] Error 127
make[1]: *** [Makefile:252: po/ja.msg] Error 127
make: *** [Makefile:1797: all] Error 2
=======> ERROR: Building '/usr/src/pkg/pkg/git#2.14.2-1.pkg.tar.gz' failed
```

**Comment by rofl0r** [comment] 2017-10-23 21:06
could you please try latest git ? there have been a number of fixes since 0.2.0

**Comment by onodera-punpun** [comment] 2017-10-23 22:13
Nope, sadly the same error.

**Comment by rofl0r** [comment] 2017-10-23 22:44
Error 127 sounds like a segfault... would you be able to catch a backtrace ?

**Comment by xhebox** [comment] 2017-10-24 15:07
@onodera-punpun cant reproduce, please provide more information, like configure options, set -x, or make V=1
```
GITGUI_VERSION = 0.21.GITGUI-dirty
    * new locations or Tcl/Tk interpreter
    MSGFMT po/zh_cn.msg     MSGFMT    po/ru.msg     MSGFMT    po/el.msg     MSGFMT po/pt_br.msg     MSGFMT    po/it.msg 366 translated, 8 fuzzy, 17 untranslated.
    MSGFMT    po/bg.msg 520 translated.
    MSGFMT    po/fr.msg 520 translated.
    MSGFMT    po/nb.msg 381 translated, 10 fuzzy.
    MSGFMT    po/hu.msg 519 translated, 1 untranslated.
    MSGFMT    po/sv.msg 474 translated, 39 untranslated.
    MSGFMT    po/vi.msg 520 translated.
    MSGFMT    po/ja.msg 547 translated.
    MSGFMT po/pt_pt.msg 514 translated.
    MSGFMT    po/de.msg 565 translated.
```

**Comment by onodera-punpun** [comment] 2017-10-24 16:59
No configure options, no CFLAGS, etc:

```
~/tmp/git-2.14.2 make V=1
make -C git-gui  gitexecdir='/home/onodera/libexec/git-core' all
make[1]: Entering directory '/home/onodera/tmp/git-2.14.2/git-gui'
tclsh po/po2msg.sh --statistics --tcl -l de -d po/ po/de.po
make[1]: tclsh: Command not found
make[1]: *** [Makefile:252: po/de.msg] Error 127
make[1]: Leaving directory '/home/onodera/tmp/git-2.14.2/git-gui'
make: *** [Makefile:1797: all] Error 2
```

I've now confirmed that it actually *does* build with normal gettext which doesn't provide `tclsh`.

**Comment by rofl0r** [comment] 2017-11-07 15:40
@onodera-punpun i committed @xhebox's fix to master, would you be so kind as to check if your issue is fixed ?

**Comment by onodera-punpun** [comment] 2017-11-08 19:15
@rofl0r @xhebox Nope, sadly it doesn't seem to work for me.

**Comment by xhebox** [comment] 2017-11-09 04:53
@onodera-punpun really sorry, try new commits again please :)  i should have tested but my scripts installed tcl automatically before my test, which means i did not test without tclsh actually.

**Comment by feizhengyang** [comment] 2023-07-07 13:18
every chekc this post : http://juniway.blogspot.com/2015/12/build-git-from-source-on-ubuntu.html
1. sudo apt-get install tcl-dev
2. sudo apt-get install gettext
3. sudo apt-get install libcurl4-openssl-dev

this works for me

**Comment by rofl0r** [comment] 2023-07-07 16:51
let's pretend this issue is fixed, since we didnt hear anything.
@feizhengyang: nice trolling.

**Closed by rofl0r** 2023-07-07 16:51 UTC
